name: Release packages

on:
  release:
    types: [published]

jobs:
  releasePackages:
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm i

      - name: Build packages
        run: npm run build
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}

      - name: Publish @astral/eslint-config-base
        run: npm publish ./packages/eslint-config-base/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @astral/eslint-config-node
        run: npm publish ./packages/eslint-config-node/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @astral/eslint-config-node-ts
        run: npm publish ./packages/eslint-config-node-ts/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @astral/eslint-config-react-ts
        run: npm publish ./packages/eslint-config-react-ts/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @astral/stylelint-config-styled
        run: npm publish ./packages/stylelint-config-styled/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @astral/commitlint-config
        run: npm publish ./packages/commitlint-config/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @astral/prettier-config
        run: npm publish ./packages/prettier-config/lib
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  notify:
    name: notify
    needs: releasePackages
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on release
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RELEASE_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            🚀 <b>Были опубликованы новые версии пакетов code style !</b>

            ⚡️ <b>ESLint</b>
            📦  @astral/eslint-config-base: ${{ github.event.release.tag_name }}
            📦  @astral/eslint-config-node: ${{ github.event.release.tag_name }}
            📦  @astral/eslint-config-node-ts: ${{ github.event.release.tag_name }}
            📦  @astral/eslint-config-react-ts: ${{ github.event.release.tag_name }}

            ⚡️ <b>Prettier</b>
            📦  @astral/prettier-config: ${{ github.event.release.tag_name }}

            ⚡️ <b>Stylelint</b>
            📦  @astral/stylelint-config-styled: ${{ github.event.release.tag_name }}

            ⚡️ <b>Commitlint</b>
            📦  @astral/commitlint-config: ${{ github.event.release.tag_name }}

            ⚡️ <a href="${{ github.event.release.html_url }}">Changelog</a>

